name: E2E Test

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 7 * * 1-6'
env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
jobs:
  e2e-test:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]

    name: RD E2E Test - ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 # required to git describe - app version info

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Build CI
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1 # do not install default pw browsers

      - name: Run Linter check
        run: npm run lint:nofix

      - name: ${{ matrix.os }} - E2E Tests
        if: ${{ matrix.os != 'ubuntu-20.04' }}
        run: npm run test:e2e

      - name: Linux xvfb - E2E Tests
        if: startsWith(matrix.os, 'ubuntu-')
        run: xvfb-run --auto-servernum -- npm run test:e2e

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: PW-E2E-Logs-${{ matrix.os }}
          path: |
            ./e2e/reports/*
